### ISSUE TITLE
Have the possibility to send a "custom event"

### ISSUE THREAD

**Issue by andrekiba** [stoiveyp/Alexa.NET.ProactiveEvents#4]
Hi Steven and thanks in advance for you amazing work :-)
This is not an issue, I just want to ask if there is a way to send e "custom event" through ProactiveEvents api.
What I'm triyng to do is to notify a user (unicast) that a task (previous launched from skill) has ended successfully or with an error. It's a very simple message so I thought that the nearest schema is `AMAZON.MessageAlert.Activated`...but here I can only specify the creator...
If there is no way...maybe I can use progressive responses? But sincerely I don't think this can be the right pattern because the task can take some minutes to complete.
It's unbelivable that they removed notifications api...

**Comment by stoiveyp** [comment]
Morning @andrekiba 

Currently Proactive events only support the released schemas, so I think MessageAlert would be your closest match - with you using creator to represent your process and get your user back into the skill.

I completely understand why progressive response might seen like an answer, but its purpose is to stop your skill having a long pause before you return the result - it still adheres to the rules about responses which is that the skill response has to be returned in 8 seconds.

It certainly sounds like Proactive Events are your primary way forward, without that you're into secondary channels, like being able to email them the information etc.

**Comment by andrekiba** [comment]
thank you Steven!
what do you mean with "and get you user back into the skill"?
Is there possibility to trigger the skill starting from a proactive event?

**Comment by stoiveyp** [comment]
The point of a proactive event is to get the user to re-launch your skill, that's all I meant.
