### ISSUE TITLE
AMAZON.Occasion.Updated Schema Update

### ISSUE THREAD

**Issue by Crispin-at-Linknode** [stoiveyp/Alexa.NET.ProactiveEvents#5]
In ReservationConfirmationStatus.cs

        [EnumMember(Value = "REQUESTED")] Requested,

should be changed to: 

        [EnumMember(Value = "RECEIVED")] Received,

Amazon return BadRequest validation from a "REQUESTED" occasion:

{
    "type": "Bad Request",
    "message": "The event failed the schema validation, eventNode does not match schema, report is com.github.fge.jsonschema.core.report.ListProcessingReport: failure\n--- BEGIN MESSAGES ---\nwarning: the following keywords are unknown and will be ignored: [$id, schemaId]\n    level: \"warning\"\n    schema: {\"loadingURI\":\"#\",\"pointer\":\"\"}\n    domain: \"syntax\"\n    ignored: [\"$id\",\"schemaId\"]\nerror: instance value (\"REQUESTED\") not found in enum (possible values: [\"CONFIRMED\",\"CANCELED\",\"RECEIVED\",\"CREATED\",\"UPDATED\",\"RESCHEDULED\"])\n    level: \"error\"\n    schema: {\"loadingURI\":\"#\",\"pointer\":\"/properties/payload/properties/state/properties/confirmationStatus\"}\n    instance: {\"pointer\":\"/payload/state/confirmationStatus\"}\n    domain: \"validation\"\n    keyword: \"enum\"\n    value: \"REQUESTED\"\n    enum: [\"CONFIRMED\",\"CANCELED\",\"RECEIVED\",\"CREATED\",\"UPDATED\",\"RESCHEDULED\"]\n---  END MESSAGES  ---\n"
}

**Comment by stoiveyp** [comment]
Thanks for this @Crispin-at-Linknode - looks like the docs are out of date:
https://developer.amazon.com/docs/smapi/schemas-for-proactive-events.html#occasion

I'll get to the update in the next 24hrs - I'll raise a support issue in the forums to get the docs updated too

**Comment by Crispin-at-Linknode** [comment]
Great - thanks. Your .NET ProactiveEvents (and other packages) help immensely in trying to get a skill with events running properly - and still the odd hiccup. Your posts on Amazon forums were very useful too.

**Comment by stoiveyp** [comment]
Updated the enum in v1.0.1
